[package]
name = "tsunami"
version = "0.11.0-beta.3"
edition = "2018"

description = "Toolkit for running short-lived jobs on cloud VMs"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>", "Akshay Narayan <akshayn@mit.edu>"]

documentation = "https://docs.rs/tsunami"
homepage = "https://github.com/jonhoo/tsunami"
repository = "https://github.com/jonhoo/tsunami.git"

keywords = ["ec2", "aws", "azure", "vm", "spot-instances", "distributed", "benchmark"]
categories = []

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/tsunami" }
maintenance = { status = "passively-maintained" }

[features]
default = ["aws", "azure", "baremetal"]
debug = ["slog/max_level_trace", "slog/release_max_level_debug"]
aws = ["rusoto_core", "rusoto_ec2", "futures-util", "rayon", "tempfile", "tokio"]
azure = ["serde", "serde_json", "rayon"]
baremetal = []
args = ["structopt"]

[dependencies]
educe = "0.4"
failure = "0.1.1"
itertools = "0.8"
rand = "0.7"
slog = "2.1.1"
slog-term = "2.4.0"
openssh = "0.4.2"
rayon = { version = "1.0.0", optional = true }
rusoto_core = { version = "0.43.0", optional = true }
rusoto_ec2 = {version = "0.43.0", optional = true }
futures-util = { version = "0.3.4", optional = true }
tempfile = { version = "3.0.0", optional = true }
tokio = { version = "0.2.0", features = ["rt-core"], optional = true }
serde_json = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true}
structopt = { version = "0.2", optional = true }

[dev-dependencies]
rusoto_sts = "0.43.0"

[profile.release]
debug = true

[[example]]
name = "launch"
required-features = ["args"]
